### ISSUE TITLE
Support of broadcasting?

### ISSUE THREAD

**Issue by Nic2012** [scalecube/socketio#35]
Hi Anton,
I am testing y framework, it works fine. Great work.
But does the APi also supports a broadcasting method from server to each connected client?
Best regards and happy new year :)
Nic

**Comment by antonkharenko** [comment]
@Nic2012 Hi, Nic. Thanks. It doesn't support broadcasting. But it's probably fairly simple to implement some basic support on top by tracking all `Session` objects received at `onConnect/Disconnect` events and then send message to each. 

Conceptually my thoughts was that Socket.IO provides a simple transport channel to mobile and web clients while features like broadcast should be handled at cluster level (e.g. send message to all clients connected to cluster of edge servers). You can also check ScaleCube Cluster here https://github.com/scalecube/scalecube

**Comment by Nic2012** [comment]
Ok thats fine.
To be honest I was thinking in first moment y example of SocketIOClient is a client. But its more a webserver hosting the demo client. So is there any real client implementation in y framework that a java app can act like a websocket client.

**Comment by antonkharenko** [comment]
Hi, 
There is no client implementation of Socket.IO protocol at this project. It is about server side Java implementation, since the main use case are web clients.

**Comment by Nic2012** [comment]
Do y have any recommendation which another git project of a Java based client impl. would work with y server?

**Comment by antonkharenko** [comment]
I don't have any specific recommendations, but you may try some available open source implementations like https://github.com/Gottox/socket.io-java-client or https://github.com/clwillingham/java-socket.io.client

**Comment by Nic2012** [comment]
Great, thank y for y support.
