### ISSUE TITLE
getting client IP if client is behind many proxies

### ISSUE THREAD

**Issue by dankata** [scalecube/socketio#40]
Hi guys,

we have a small issue using socketio lib. 

If client is behind load balancer clientIp is in some of the http message headers. Most often it is 'X-Forwarded-For' header or some custom one. This is covered setting remoteAddressHeader in configuration of ServerConfiguration.

Our problem is when client is behind many proxies - e.g two load balancers. In this case default behavior of load balancer is to append IPs to the header. For example if client IP is 40.40.40.40 and LB1 IP is 50.50.50.50 in 'X-Forwarded-For' we will have:

1st LB -> add 40.40.40.40 in 'X-Forwarded-For' header
2nd LB -> appends LB1 IP to the header

so we receive 
HEADER: X-Forwarded-For = 40.40.40.40, 50.50.50.50

The general format of the field is:
X-Forwarded-For: client, proxy1, proxy2
(wikipedia: [https://en.wikipedia.org/wiki/X-Forwarded-For])

So is it possible to modify PipelineUtils.getHeaderClientIPParamValue to handle this case. 

Thanks in advance,
Daniel

**Comment by armangal** [comment]
@antonkharenko   Privet

**Comment by antonkharenko** [comment]
Hello and privet :)

Yes, it is possible to modify behavior, but what is the expected one in such case? I mean that then to get client IP you use Session interface `getRemoteAddress()` method, so should it return first address in the coma-separated list? should there be a possibility to get the full value of 'X-Forwarded-For' header? WDYT?

**Comment by armangal** [comment]
Since the final value will be in the following format:
X-Forwarded-For: client, proxy1, proxy2
You should know exactly the client IP, it's the first one.
But maybe you can add additional method that will return the whole thing also... not that I understand much, I'm just a manager ;)\

**Comment by dankata** [comment]
We now use it like this:
```
if (ip != null) {
ip = ip.split(",")[0];
}
```
this will keep current functionality as is and if header contains many IPs comma separated will return correct one.

Getting full value of specific header also will do the work.

Thanks,
Daniel

**Comment by antonkharenko** [comment]
@dankata please check PR: https://github.com/scalecube/socketio/pull/42

**Comment by dankata** [comment]
Great,

we're waiting for the release :)

**Comment by antonkharenko** [comment]
Fixed by PR https://github.com/scalecube/socketio/pull/42. And released new version `2.3.2` which contains following fix.

**Comment by ronenhamias** [comment]
@armangal and @dankata this project is open source everyone are free to suggest a pr and fix
your contribution is more than welcome we need your support :)
